# Site settings
title: 浅隐听寒
email: lgc1434649345@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://qianyintinghan.github.io" # the subpath of your site, e.g. /blog/
#baseurl: ""
url: "https://qianyintinghan.github.io" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000/"
twitter_username: qianyintinghan
github_username:  qianyintinghan
twitter: qianyintinghan
# Build settings
markdown: kramdown
